#!/bin/bash
################################################################################
# AIFX v2 - Stop All Services Script
#
# This script stops all AIFX v2 services running in tmux
#
# Usage:
#   ./stop-all-services.sh
#
# Generated by Claude Code
################################################################################

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

echo "=============================================================================="
echo "              AIFX v2 - Stopping All Services                               "
echo "=============================================================================="
echo ""

# Stop Backend
if tmux has-session -t aifx-backend 2>/dev/null; then
    log_info "Stopping Backend..."
    tmux kill-session -t aifx-backend
    log_success "Backend stopped"
else
    log_warning "Backend session not found (may already be stopped)"
fi

# Stop Frontend
if tmux has-session -t aifx-frontend 2>/dev/null; then
    log_info "Stopping Frontend..."
    tmux kill-session -t aifx-frontend
    log_success "Frontend stopped"
else
    log_warning "Frontend session not found (may already be stopped)"
fi

# Stop ML Engine
if tmux has-session -t aifx-ml 2>/dev/null; then
    log_info "Stopping ML Engine..."
    tmux kill-session -t aifx-ml
    log_success "ML Engine stopped"
else
    log_warning "ML Engine session not found (may already be stopped)"
fi

echo ""
echo "=============================================================================="
echo "                    All Services Stopped! ✅                                 "
echo "=============================================================================="
echo ""
